# Generated by Django 5.0.6 on 2024-06-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_transaction_balance_after_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='balance_after_borrowing',
            field=models.IntegerField(default=0),
        ),
    ]
