# Generated by Django 5.0.6 on 2024-06-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userbankaccount_balance_after_borrowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='balance_after_borrowing',
        ),
    ]
