# Generated by Django 5.0.6 on 2024-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='borrowed_books',
            field=models.ManyToManyField(related_name='borrowers', through='books.BorrowedBook', to='books.book'),
        ),
    ]
