# Generated by Django 5.0.6 on 2024-06-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrowedbook_borrowing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrowing_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
