# Generated by Django 5.0.6 on 2024-06-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_borrowedbook_borrowing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='balance_after_borrowing',
        ),
    ]
