# Generated by Django 5.0.6 on 2024-06-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_borrowedbook_is_returned'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowedbook',
            unique_together=set(),
        ),
    ]
