# Generated by Django 5.0.6 on 2024-06-21 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_borrowedbook_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='borrowed_books',
        ),
    ]
